from selenium.webdriver.common.by import By

logo = (By.CSS_SELECTOR, "[alt='CUBUX Logo']")
title = (By.CSS_SELECTOR, '.no-margin .title')
operations_list = (By.CSS_SELECTOR, '.value-block')
execute_operation_btn = (By.CSS_SELECTOR, '.value-block button')
options = (By.CSS_SELECTOR, '.hex-text')
under_options = (By.CSS_SELECTOR, '.hex-select-list .hex-text')
date_picker = (By.CSS_SELECTOR, '.react-datepicker__day')
amount = (By.CSS_SELECTOR, '.currency')
repetition = (By.CSS_SELECTOR, '.rc-dialog-body select')
days_of_month = (By.CSS_SELECTOR, '.RepeatCheckList_text__p-QHD')
ok_btn = (By.CSS_SELECTOR, '.modal-buttons>.btn')
total_amount = (By.CSS_SELECTOR, '.inline>.value')
categories = (By.CSS_SELECTOR, '.list-first')
amounts = (By.CSS_SELECTOR, '.list-value._large')
transactions = (By.CSS_SELECTOR, '.TransactionsTable_root__ehmR3  tr')
operations = (By.CSS_SELECTOR, '.list-symbol>button')
confirm_dialog = (By.CSS_SELECTOR, '.ConfirmDialog_buttons__WCKvf>button')
transactions_form = (By.CSS_SELECTOR, '.scrollbar')
no_transactions_msg = (By.CSS_SELECTOR, "[colspan='6']")
